### ISSUE TITLE
Logger.format() can't process args with positions

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-log#100]

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-log#100` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-log#100` was not in scope

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#unknown]() is still not solved.
