### ISSUE TITLE
Logger fails to build complex strings with positional substitutes

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-log#103]

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.3`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-log#103` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#103](https://github.com/jcabi/jcabi-log/issues/103) was not in scope
