### ISSUE TITLE
depends on mockito-core as compile scope, is a mistake?

### ISSUE THREAD

**Issue by ningpp** [jcabi/jcabi-log#134]
https://github.com/apache/tinkerpop/pull/1836

**Comment by ningpp** [comment]
hello?

**Comment by ningpp** [comment]
hello?

**Comment by ningpp** [comment]
hello???

**Comment by ningpp** [comment]
hello！

**Comment by ChristopherWirt** [comment]
+1

**Comment by goodale** [comment]
+1   this looks to be a bug as mockito-core should be scoped as 'test' so it isn't pulled into artifacts which use jcabi-manifests, etc.

**Comment by yegor256** [comment]
@goodale this was definitely a bug, I'm sorry I missed your ticket. Fixed in a84c76a
