### ISSUE TITLE
Logger.format should be moved

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-log#19]
``Logger.format`` doesn't look like a method that should be inside a Logger, more like an utility method.
It looks confusing when ``Logger.format()`` is used outside logging context in other projects.
Maybe create jcabi-lang (similar to commons-lang) for such general utility methods that don't belong to other projects.

**Comment by yegor256** [comment]
@krzyk we won't move this method out. even though the idea is good, making utility classes is not a good strategy. let's keep it inside jcabi-log
