### ISSUE TITLE
Decor 'msec' not found and class can't be instantiated

### ISSUE THREAD

**Issue by volodya-lombrozo** [jcabi/jcabi-log#205]
I have the following log statement:

```java
Logger.info(
    this, 
    "We made %d attempts to convert bytecode to xmir and back in %[msec]s",
    attempts,
    100L
);
```

When I run it, I get:

```
We made 100 attempts to convert bytecode to xmir and back in [Decor 'msec' not found and class can't be instantiated]
```

**Expected behaviour:**

```
We made 100 attempts to convert bytecode to xmir and back in 100ms
```

The [documentation](https://github.com/jcabi/jcabi-log) states:

> %[msec]s --- milliseconds ➜ ms, sec, min, hours, etc.

Please, fix the documentation or the code.

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you help, please?

**Comment by yegor256** [comment]
@volodya-lombrozo it's a typo in documentation, use `%[ms]s` instead

**Comment by volodya-lombrozo** [comment]
@yegor256 Works like a charm. Thank you.
