### ISSUE TITLE
VerboseProcessTest.java:52-55: Locale/encoding problem in two test...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-log#24]
Puzzle `18-de8643f2` in `src/test/java/com/jcabi/log/VerboseProcessTest.java:52-55` has to be resolved: Locale/encoding problem in two test methods here. I'm not sure how to fix them, but they should be fixed. They fail on some machines, while run perfectly on others. They also fail when being executed from IntelliJ.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by cyberone** [comment]
@yegor256 I had only runsACommandLineScriptWithException failing. To fix two others I need failing logs. Where can I get them?

**Comment by yegor256** [comment]
@cyberone I don't have them. They don't fail for me any more. Maybe this link will help you http://stackoverflow.com/questions/24802042/how-to-handle-encoding-inside-processbuilder-commands I created this question when the tests were failing

**Comment by cyberone** [comment]
@yegor256 I'm having echoesUnicodeCorrectly method with the following asswertion:

    Expected: a string containing "0000000 d1 82 d0 b5 d1 81 d1 82"
     but: was "0000000 82d1 b5d0 81d1 82d1               

this means that a problem is in hexdump command which differs on some OSes. Which OS did you run this test on?

**Comment by yegor256** [comment]
@cyberone Mac OSX in my case. Maybe it's possible to tell `hexdump` how to format the output?

**Comment by dmarkov** [comment]
@cyberone you're holding this ticket for 13 days already. If it's not finished (and closed) in the next 16 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. do not forget to remove the TODO puzzle from the source code. -30 added to your rating, current score is: [-250](http://www.netbout.com/b/35076?open=rating)

**Comment by dmarkov** [comment]
@cyberone the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html). added -60 to your rating, now it is equal to [-730](http://www.netbout.com/b/35076?open=rating)

**Comment by dmarkov** [comment]
@aoxa it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket. The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmarkov** [comment]
@aoxa you're working with this ticket for the last 15 days. If it's not closed within the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... do not forget to remove the TODO puzzle from the source code... -30 added to your rating, current score is: -180

**Comment by aoxa** [comment]
I've tried a bunch of encoding after reading the process result while executing echosUnicodeCorrectly test, but could not found the reason why it is failing. I'm getting always the 0000000 f2 e5 f1 f2, except for UTF16 where a bunch of japanese chars appear. In my terminal I've ran...
:~$ echo -n тест | hexdump
0000000 82d1 b5d0 81d1 82d1                    
0000008
:~$ /bin/bash -c echo -n тест | hexdump
0000000 000a                                   
0000001

which surprisingly enough gave two different results. I'm not being able to understand the reason for the failure, so please reassign the issue.
My OS is Ubuntu 14.04

**Comment by yegor256** [comment]
@dmarkov assign someone else here pls

**Comment by dmarkov** [comment]
> @dmarkov assign someone else here pls

@yegor256 no problem, I'll try to find somebody else

**Comment by dmarkov** [comment]
@apocarteres please proceed, it's yours

**Comment by dmarkov** [comment]
@yegor256 Closing this issue now...
