### ISSUE TITLE
ObjectDecorTest.java:66-71: Let's handle arrays. For now,...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-log#44]
Puzzle `31-6c930351` in `src/test/java/com/jcabi/log/ObjectDecorTest.java:66-71` has to be resolved: Let's handle arrays. For now, ObjectDecor only does a deepToString of array contents. Let's make it so that each of its members will also show its internal contents. Ensure that this is handled in a "deep" fashion; that is, if its members are also arrays, then print the contents of the members of that array member (and so on). When done, uncomment the last test case below.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@jenya the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html)... -60 added to your rating, current score is: [-555](http://www.netbout.com/b/35092?open=rating)

**Comment by dmarkov** [comment]
@cyberone could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here; The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by cyberone** [comment]
@dmarkov please review https://github.com/jcabi/jcabi-log/pull/50

**Comment by cyberone** [comment]
@dmarkov the PR is merged and closed, please close the issue

**Comment by dmarkov** [comment]
The issue should be closed..

**Comment by dmarkov** [comment]
@cyberone I added **30 mins** to your account, many thanks for working with the project!; +30 to your rating, your total score is [-640](http://www.netbout.com/b/35076?open=rating)
