### ISSUE TITLE
Need a way to switch coloring off

### ISSUE THREAD

**Issue by longtimeago** [jcabi/jcabi-log#54]
Coloring looks really cool in terminal. Unfortunately, we also have traces.
Look at these traces http://www.rultor.com/t/2130-75708892. You can find a lot of entries, started from
```
[0;37mINFOm] ...
```
It would be grate if there will be a way to switch coloring off, for example, through system property:
```
-Dcom.jcabi.log.coloring=false
```

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@longtimeago good idea about system property, thanks

**Comment by dmarkov** [comment]
@longtimeago thanks for reporting! I topped your account for 15 mins, transaction 59894043

**Comment by longtimeago** [comment]
@yegor256 you are welcome! Better later than never :)

**Comment by longtimeago** [comment]
@yegor256 could you please assign someone here?
The bug is annoying ...

**Comment by dmarkov** [comment]
@suseika it's your task now, go ahead

**Comment by Suseika** [comment]
@dmarkov I need more time

**Comment by dmarkov** [comment]
> @dmarkov I need more time

@suseika sure, take your time

**Comment by Suseika** [comment]
@longtimeago Implemented, see PR #61

**Comment by longtimeago** [comment]
@Suseika thank you very much!

**Comment by longtimeago** [comment]
@yegor256 could you please release a new version with these changes?

**Comment by yegor256** [comment]
@rultor release, tag is `0.17`

**Comment by dmarkov** [comment]
@suseika Thanks for your contribution, **30 mins** was added to your account, payment ID is `AP-92B32428XY9566334`, 407 hours and 56 mins spent total; +30 added to your rating, at the moment it is: [+871](http://www.netbout.com/b/35381?open=rating)

**Comment by dmarkov** [comment]
@longtimeago once `54-5ce25827`/#63 puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by dmarkov** [comment]
@longtimeago the last puzzle `63-fcb6d07a`/#77 solved
