### ISSUE TITLE
MulticolorLayout needs to be refactored

### ISSUE THREAD

**Issue by Suseika** [jcabi/jcabi-log#59]
This class does too much, its private functionality should be spread among multiple classes. It does formatting, parsing, coloring and managing human-readable color names, when it should only be doing formatting (as an EnhancedPatternLayout descendant). This is preventing me from fixing #53.

**Comment by Suseika** [comment]
@dmarkov Please assign me to this.

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by dmarkov** [comment]
@suseika many thanks for the bug report, I added 15 mins to your acc, transaction `AP-9K060333KD603460G`

**Comment by dmarkov** [comment]
@piddubnyi please help, the task is yours

**Comment by piddubnyi** [comment]
@Suseika Initial change is done in #72. Additional puzzles created to proceed on refactoring.
Please close this one.

**Comment by dmarkov** [comment]
@suseika the code made here contains a puzzle `59-498fab78`/#75, which will be resolved soon

**Comment by dmarkov** [comment]
@piddubnyi Much appreciated! **30 mins** was added to your account, payment ID `76501906`, time spent is 141 hours and 10 mins; +30 added to your rating, at the moment it is: [+240](http://www.netbout.com/b/35966?open=rating)

**Comment by dmarkov** [comment]
@suseika the last puzzle `59-498fab78`/#75 originated from here solved
