### ISSUE TITLE
Getting %L parameter to work

### ISSUE THREAD

**Issue by AlexAbraham1** [jcabi/jcabi-log#60]
Hey!

I was wondering if there is a way to get the %L parameter in layout.ConversionPattern to work. Right now it gives me the line number of the log statement in the Logger class and it would be much better if I could get the line number in the class I called the static method.

EX: log4j.appender.CONSOLE.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} [%color{%-5p}] %c:%L - %m%n

Thanks!

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@AlexAbraham1 seems like a bug, thanks for reporting, we'll see what we can do

**Comment by dmarkov** [comment]
@suseika it's your task now

**Comment by Suseika** [comment]
@dmarkov Please assign someone else

**Comment by dmarkov** [comment]
> @dmarkov Please assign someone else

@suseika -30 points to your rating

**Comment by dmarkov** [comment]
> @dmarkov Please assign someone else

@suseika I will try to find someone else

**Comment by dmarkov** [comment]
@pecko this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here; The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by pecko** [comment]
@dmarkov @yegor256 

I have created the PR: https://github.com/jcabi/jcabi-log/pull/65
It uses reflection, but I don't know to solve it in another way.

**Comment by dmarkov** [comment]
> @dmarkov @yegor256 
> 
> I have created the PR: https://github.com/jcabi/jcabi-log/pull/65
> It uses reflection, but I don't know to solve it in another way.

@pecko OK we'll review

**Comment by pecko** [comment]
@dmarkov 

@dmzaytsev and @yegor256 already reviewed it. See https://github.com/jcabi/jcabi-log/pull/65

**Comment by dmarkov** [comment]
> @dmarkov 
> 
> @dmzaytsev and @yegor256 already review it. See https://github.com/jcabi/jcabi-log/pull/65

@pecko OK thanks

**Comment by dmarkov** [comment]
@pecko just a reminder that you're working with this task for 16 days already. -30 added to your rating, at the moment it is: [+105](http://www.netbout.com/b/35660?open=rating)

**Comment by pecko** [comment]
@dmarkov 

It's finished 17 days ago, reviewed and deployed 3 days ago. See https://github.com/jcabi/jcabi-log/pull/65#issuecomment-148675253

**Comment by yegor256** [comment]
@pecko keep in mind that the task is finished when the ticket is closed, by its author, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by AlexAbraham1** [comment]
Really sorry guys I forgot about this issue

I closed the issue now :)

Thanks to everyone who helped resolve it!
