### ISSUE TITLE
MulticolorLayoutTest.java:44-56: Create an integration test for...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-log#63]
Puzzle `54-5ce25827` in `src/test/java/com/jcabi/log/MulticolorLayoutTest.java:44-56` has to be resolved: Create an integration test for testing if MulticolorLayout will disable text coloring when an application is run with `-Dcom.jcabi.log.coloring=false`. ... Intergration testing is required because this can't be done in a unit test: ... - We can't just pass a parameter to `MulticolorLayout` that determines if the layout should color its output, because Log4J requires EnhancedPatternLayout to have a 0-arguments constructor. - We can't disable coloring with something like `MulticolorLayout#setColoring(boolean)`, too, (that would be unit-testable) because Log4J won't know how to call that. - `System.getProperty(String)` is not mockable for obvious reasons.... The puzzle was created by Suseika on 11-Aug-2015.

If you have any technical questions, don't ask me, submit new tickets instead

<hr id='w'>

**Comment by dmarkov** [comment]
@amihaiemil This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here

The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by amihaiemil** [comment]
@dmarkov The PR for this was reviewed and is waiting for Yegor's approval.

**Comment by dmarkov** [comment]
> @dmarkov The PR for this was reviewed and is waiting for Yegor's approval.

@amihaiemil OK

**Comment by amihaiemil** [comment]
@dmarkov The PR for this still waits for @yegor256 approval to merge. He did not reply since 6 days ago.

**Comment by dmarkov** [comment]
@amihaiemil you're working with this ticket for the last 15 days. If it is not closed within the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck; as a reminder, don't forget to remove the `@todo` puzzle from the source code; -30 to your rating, your total score is [+0](http://www.netbout.com/b/36402?open=rating)

**Comment by amihaiemil** [comment]
@dmarkov The task is done and reviewed, it simply waits for @yegor256 's approval to merge. What can I do more about it? Can someone else take care of it if Yegor does not have the time?

**Comment by amihaiemil** [comment]
@dmarkov If no one else can be assigned to review and let rultor merge, can we just wait for Yegor? I finished working on it 9 days ago. Since then, I've been waiting for feedback and already let 5 or 6 messages for Yegor to see.

**Comment by dmzaytsev** [comment]
@amihaiemil just type `@dmarkov I need more time`

**Comment by amihaiemil** [comment]
@dmarkov I need more time

**Comment by dmarkov** [comment]
> @dmarkov The PR for this still waits for @yegor256 approval to merge. He did not reply since 6 days ago.

@amihaiemil ping him here

**Comment by dmarkov** [comment]
> @dmarkov I need more time

@amihaiemil OK, no problem, take your time

**Comment by amihaiemil** [comment]
@yegor256 Please don't forget to give feedback on the PR for this issue: #73

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by amihaiemil** [comment]
@yegor256 The PR #73 for this issue is still waiting for merge approval.

**Comment by amihaiemil** [comment]
@yegor256 ping. See #73

**Comment by amihaiemil** [comment]
@dmarkov This needs more time. The task is done, PR is created and reviewed and still waiting for Yegor's approval to merge.

**Comment by amihaiemil** [comment]
@dmarkov The PR #73 for this issue has been merged and closed. This ticket can be closed as well. Thanks.

**Comment by amihaiemil** [comment]
@dmarkov ping

**Comment by amihaiemil** [comment]
@dmarkov Can you close this? Thanks

**Comment by amihaiemil** [comment]
@dmarkov close this pls

**Comment by dmarkov** [comment]
> @dmarkov This needs more time. The task is done, PR is created and reviewed and still waiting for Yegor's approval to merge.

@amihaiemil sure, take your time, I know about this pause

**Comment by dmarkov** [comment]
> @dmarkov The PR #73 for this issue has been merged and closed. This ticket can be closed as well. Thanks.

@amihaiemil OK

**Comment by dmarkov** [comment]
> @dmarkov ping

@amihaiemil I will close automatically, if you removed the puzzle and deployment cycle is not broken

**Comment by dmarkov** [comment]
@yegor256 the code made here contains a puzzle `63-fcb6d07a`/#77, which will be resolved soon

**Comment by dmarkov** [comment]
@yegor256 The task is closed, thanks everybody

**Comment by dmarkov** [comment]
@amihaiemil thanks, I just added **30 mins** to your account, payment `AP-1NP34462WR292830D`, 767 hours and 17 mins spent

added +30 to your rating, now it is equal to [+45](http://www.netbout.com/b/36402?open=rating)

**Comment by dmarkov** [comment]
@yegor256 the last puzzle `63-fcb6d07a`/#77 originated from here solved
