### ISSUE TITLE
Consider upgrade to log4j2

### ISSUE THREAD

**Issue by longtimeago** [jcabi/jcabi-log#67]
It would be really cool to have all log4j features available, such as 
https://logging.apache.org/log4j/2.x/faq.html#separate_log_files

This is really useful feature to write logs into separate files per some key.

**Comment by longtimeago** [comment]
@yegor256 could you please consider resolution of the issue?

**Comment by yegor256** [comment]
@longtimeago but we don't work with log4j anyhow in this library. We only communicate with slf4j. Or I missed something?

**Comment by longtimeago** [comment]
@yegor256 Yes, log4j is optional but we use it for `MulticolorLayout`.
`PatternLayout` from log4j2 supports coloring.
So we could upgrade to log4j2, get rid of `MulticolorLayout` and have all other nice features from log4j2

**Comment by yegor256** [comment]
@longtimeago yeah, right, but we don't need any other features from log4j :) MulticolorLayout is the only place where we use log4j. Maybe it's time to just delete it, since log4j2 supports colors out of the box?

**Comment by longtimeago** [comment]
@yegor256 Yes, this is good option :)
In this case clients which still want coloring would have to use migrate on log4j2.
Beware, it's not a straightforward process. One thing I know is that log4j2 does not support configuration in property files, xml only

**Comment by longtimeago** [comment]
@yegor256 can we proceed here?

**Comment by yegor256** [comment]
@longtimeago I gave it another thought... what is the point of removing it? we have users, the class is rather convenient. what exactly is the goal?

**Comment by longtimeago** [comment]
@yegor256 I thought again ... looks like you are right. There is no reason in removing `MulticolorLayout` as well as well as removing optional dependency on log4j.
