### ISSUE TITLE
Documentation doesn't mention how to log exceptions

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-log#68]
I can't find in documentation (README.md, javadocs or log.jcabi.com) how to log exceptions (exception name + message + stacktrace).
Please add example into README.md and javadoc of `Logger` on how to log exceptions.

**Comment by dmarkov** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://www.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@krzyk this page explains it: http://log.jcabi.com/decors.html

```
Logger.info(this, "failure: %[exception]s", ex);
```
