### ISSUE TITLE
VerboseProcess should fail if logging level was initialized to Level.ALL

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-log#74]
Very often `VerboseProcess` is used with following parameters:

```
new VerboseProcess(builder, Level.ALL, Level.ALL);
```

Which contrary to most people assumptions doesn't make the `VerboseProcess` log all the events but makes it log none of them (`Level.ALL` is lower than `Level.FINEST`, and very few projects set the log level to `FINEST`).

`VerboseProcess` should fail if created with `Level.ALL` parameters.

**Comment by dmarkov** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@krzyk well... isn't it a bit harsh? you don't see any possible use case where `Level.ALL` may be used?

**Comment by krzyk** [comment]
@yegor256 I haven't seen such a use case, even if one would like to ignore the output it could be done using logger configuration.
I think that more harm is done by allowing Level.ALL then completely forbidding it.

For me classes/objects should cause least surprise when used, doing `new VerboseProcess(builder, Level.ALL, Level.ALL);` looks good, I'll have everything logged, but in reality I'm surprised that I don't see any output from the process.

That's might be mine misunderstanding of the class (and not reading the javadoc :) ), but when I look at the use cases in other projects, I almost always see it is used this way, which causes long debugging sessions until you findout it was the problem with logging level.

**Comment by krzyk** [comment]
@yegor256 what do you think? Do you have any other ideas how to inform the user that `Level.ALL` is not appropriate in most cases (if not all)?

**Comment by yegor256** [comment]
@krzyk OK, I agree, let's throw an exception when `Level.ALL` is specified

**Comment by dmarkov** [comment]
@krzyk thanks for the report, I topped your acc for 15 mins, payment ID `84047917`

**Comment by dmarkov** [comment]
@prondzyn please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

**30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by prondzyn** [comment]
@krzyk I did not analyzed what VerboseProcess do but according to [java.util.logging.Level docs](https://docs.oracle.com/javase/7/docs/api/java/util/logging/Level.html) `Level.ALL`:

> ALL indicates that all messages should be logged.

So what is wrong with `new VerboseProcess(builder, Level.ALL, Level.ALL);` here? According to docs all messages should be logged. Maybe the error is elsewhere?

**Comment by krzyk** [comment]
@prondzyn ALL is a setting for the log4j.xml (or properties) file, it is not meant to be used from the code for logging.

**Comment by prondzyn** [comment]
@krzyk understand. One more question - should it throw exception when both stdout and stderr are set to ALL or even if only one is set to ALL?

**Comment by krzyk** [comment]
@prondzyn It should throw exception if any of them is set to ALL

**Comment by prondzyn** [comment]
@dmarkov PR #88 is ready for this.

**Comment by dmarkov** [comment]
> @dmarkov PR #88 is ready for this.

@prondzyn thanks

**Comment by prondzyn** [comment]
@dmarkov need more time. Still waiting on @yegor256 's merge approval in #88

**Comment by dmarkov** [comment]
> @dmarkov need more time. Still waiting on @yegor256 's merge approval in #88 

@prondzyn yes, take your time, thanks for letting me know

**Comment by prondzyn** [comment]
@dmarkov I need more time. I'm waiting on @yegor256 's answer in #88

**Comment by dmarkov** [comment]
> @dmarkov I need more time. I'm waiting on @yegor256 's answer in #88

@prondzyn yeah, I know, take your time

**Comment by prondzyn** [comment]
@dmarkov I need more time. I'm waiting on @yegor256 's confirmation in #88

**Comment by dmarkov** [comment]
> @dmarkov I need more time. I'm waiting on @yegor256 's confirmation in #88

@prondzyn take your time, I am aware that we're waiting here

**Comment by prondzyn** [comment]
@dmarkov I need more time. Still waiting on @yegor256's confirmation.

**Comment by dmarkov** [comment]
> @dmarkov I need more time. Still waiting on @yegor256's confirmation.

@prondzyn sure, take your time, I know about this pause

**Comment by prondzyn** [comment]
@dmarkov do you know how long this pause will take?

**Comment by prondzyn** [comment]
@dmarkov I need more time. Still waiting on @yegor256's confirmation.

**Comment by dmarkov** [comment]
> @dmarkov I need more time. Still waiting on @yegor256's confirmation.

@prondzyn take your time, I am aware that we're waiting here

**Comment by prondzyn** [comment]
@dmarkov I need more time. Still waiting on @yegor256's confirmation.

**Comment by dmarkov** [comment]
> @dmarkov I need more time. Still waiting on @yegor256's confirmation.

@prondzyn sure, take your time, I know about this pause

**Comment by prondzyn** [comment]
@dmarkov I need more time. Still waiting on @yegor256's confirmation.

**Comment by dmarkov** [comment]
> @dmarkov I need more time. Still waiting on @yegor256's confirmation.

@prondzyn sure, take your time, I know about this pause

**Comment by prondzyn** [comment]
@krzyk PR #88 merged. Please close the task.

**Comment by krzyk** [comment]
@prondzyn thanks

**Comment by dmarkov** [comment]
@prondzyn Thank you, I have added **30 mins** to your account in payment/transaction "`AP-9SL850281L944471W`", time consumed: 1824 hours and 32 mins

+30 to your rating, your total score is [+90](http://www.netbout.com/b/35715?open=rating)
