### ISSUE TITLE
MulticolorLayout.java:84-85: This class is still handling...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-log#75]
Puzzle `59-498fab78` in `src/main/java/com/jcabi/log/MulticolorLayout.java:84-85` has to be resolved: This class is still handling multiple responsibilities like formatting, parsing and coloring and should be refactored.... The puzzle was created by Igor Piddubnyi on 29-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by dmarkov** [comment]
@jrdalpra it's your task, go ahead

**Comment by jrdalpra** [comment]
@dmarkov ok

**Comment by dmarkov** [comment]
> @dmarkov ok

@jrdalpra thanks

**Comment by jrdalpra** [comment]
@dmarkov the PR #76 is ready for review. Thanks.

**Comment by jrdalpra** [comment]
@dmarkov any reviewer for the PR #76 ? thanks.

**Comment by dmarkov** [comment]
> @dmarkov the PR #76 is ready for review. Thanks.

@jrdalpra thanks, will take a look

**Comment by jrdalpra** [comment]
@dmarkov the PR #76 was merged. Thanks.

**Comment by dmarkov** [comment]
> @dmarkov any reviewer for the PR #76 ? thanks.

@jrdalpra still waiting to find the right one

**Comment by dmarkov** [comment]
> @dmarkov the PR #76 was merged. Thanks.

@jrdalpra thanks for that

**Comment by dmarkov** [comment]
@yegor256 The issue is closed

**Comment by dmarkov** [comment]
@jrdalpra done, I added **30 mins** in payment `AP-9J343123PV982513N`, 409 hours and 8 mins spent to complete this. +30 added to your rating, current score is: [+248](http://www.netbout.com/b/36044?open=rating)
