### ISSUE TITLE
MulticolorLayoutTest.java:44-51: Fix bug in method format(LoggingEvent)....

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-log#77]
Puzzle `63-fcb6d07a` in `src/test/java/com/jcabi/log/MulticolorLayoutTest.java:44-51` has to be resolved: Fix bug in method format(LoggingEvent). The tests disablesOverridenConstantColor() and disablesConstantColor() from /src/it/it-decoloring/.../MulticolorLayoutITCase are currently failing and are ignored. Problem is that the text isn't decolored correctly when the color is specified in the conversion pattern. E.g. "[%color-blue{%p}] %color-blue{%m}" .... The puzzle was created by Mihai Andronache on 1-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by dmarkov** [comment]
@amihaiemil it's in your hands now, please proceed

**Comment by amihaiemil** [comment]
@dmarkov I created PR #78 .Please assign a reviewer. Thanks.

**Comment by dmarkov** [comment]
> @dmarkov I created PR #78 .Please assign a reviewer. Thanks. 

@amihaiemil OK, sure

**Comment by amihaiemil** [comment]
@dmarkov PR #78 , concerning this issue, has been merged and closed. Please deploy it and close this issue. Thanks.

**Comment by dmarkov** [comment]
> @dmarkov PR #78 , concerning this issue, has been merged and closed. Please deploy it and close this issue. Thanks.

@amihaiemil OK

**Comment by dmarkov** [comment]
@yegor256 Thanks, closed

**Comment by dmarkov** [comment]
@amihaiemil paid, thanks, added **30 mins** to your account, payment `AP-7SX02577RW429631Y`, 193 hours and 46 mins was spent; +30 added to your rating, at the moment it is: [+135](http://www.netbout.com/b/36402?open=rating)
