### ISSUE TITLE
Provide methods that don't check the log level internally

### ISSUE THREAD

**Issue by essobedo** [jcabi/jcabi-log#79]
Up to now all the methods check internally the log level probably to avoid having to do it manually in the code because we can consider that it pollutes it with tests checking for the log level. It is interesting for readability but it is a mistake for performance reasons, let me explain why with a simple use case:

 `Logger.debug(this, "method #bar(%d) was called", this.value());`

Here we log a message in case the debug mode is enabled, in any cases this will be executed so we will still create an array of parameters and we will still evaluate the parameters even if we simply turned off the logger. We may say that it is not so costly in term of performances which is wrong because we could call it million times and more important we have no idea how much time it takes to evaluate the parameters, for example here `this.value()` could internally access to a critical section or do a slow computing which would be a performance killer.

Up to now If I can still wrap it into a if like expected, but if the corresponding log level is enabled I will check twice so it is still not an ideal/acceptable solution

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@essobedo make sense, but what do you propose? remember, it's Java

**Comment by essobedo** [comment]
@yegor256 If it was not a pure procedural approach based on static methods, I would have proposed to rewrite the code to propose a more OO approach with an interface, a default implementation that only logs the message and a decorator that checks if the log level is enabled to be able to propose both possibilities the old one that checks internally the log level before logging the message and the new one that let the user tests the log level manually and simply log the message.

If we don't want to modify the code too much and keep this approach based on statics methods, we can still propose additional static methods that will only log the message without checking the log level.

BTW getting internally the logger with `Logger.logger(source)` at each call doesn't seem to be good for performances too.

**Comment by yegor256** [comment]
@essobedo so you're suggesting something like `Logger.infoForced()`?

**Comment by essobedo** [comment]
@yegor256 yes something like that

**Comment by yegor256** [comment]
@essobedo OK, make sense, we'll implement it

**Comment by dmarkov** [comment]
@essobedo thank you for the ticket reported, I topped your account for 15 mins, transaction `91604758`

**Comment by dmarkov** [comment]
@prondzyn please proceed, it's yours

**Comment by prondzyn** [comment]
@dmarkov PR #82 prepared.

**Comment by dmarkov** [comment]
> @dmarkov PR #82 prepared.

@prondzyn thank you

**Comment by prondzyn** [comment]
@essobedo methods added. Please close the task.

**Comment by essobedo** [comment]
@prondzyn good news thx

**Comment by dmarkov** [comment]
@prondzyn thanks, I just added **30 mins** to your account, payment `AP-8UX5251217671435V`, 142 hours and 58 mins spent. +30 added to your rating, current score is: [+90](http://www.netbout.com/b/35715?open=rating)
