### ISSUE TITLE
Create and configure log files 

### ISSUE THREAD

**Issue by Stuk4** [jcabi/jcabi-log#80]
Hi, 
What i have to do for generate log files ? 
Im using logback with slf4j and I have a logback.xml. I wish to use jcabi-log.

Thanks

**Comment by Stuk4** [comment]
Is lo4j.properties

**Comment by Dingmin** [comment]
sorry,i want to ask where to glance the log,is it log in a flie? i use it to log but i can't find the log.

**Comment by Stuk4** [comment]
Do you have log4j.properties in resources path?, You can configurate the log path in this file.
