### ISSUE TITLE
Mysterious code inside VerboseRunnable

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-log#81]
There is a strange *nop* code inside `VerboseRunnable` (https://github.com/jcabi/jcabi-log/blob/d1bf0b962a4a9a2924021e1eccdeac97eacc9753/src/main/java/com/jcabi/log/VerboseRunnable.java#L214-L218):
```
        try {
            TimeUnit.MICROSECONDS.sleep(1L);
        } catch (final InterruptedException ex) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException(ex);
        }
```
Why a `VerboseRunnable` should wait 1 microsecond after executing a runnable?
The above code looks like useless, if it really is it should be removed.

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@krzyk if I remove it, this test fails: https://github.com/jcabi/jcabi-log/blob/master/src/test/java/com/jcabi/log/VerboseRunnableTest.java#L153-L194 let me think what this all is really about...

**Comment by yegor256** [comment]
@krzyk I made it a bit more clear: 1c489aa

**Comment by yegor256** [comment]
@krzyk make sense now?

**Comment by krzyk** [comment]
@yegor256 yes, now it is clear :)

**Comment by mkordas** [comment]
@yegor256 can we do a release here?

**Comment by mkordas** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.2`
