### ISSUE TITLE
Add handling of suppliers in log statements

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-log#83]
Right now to avoid doing evaluation of expression provided to the logger one has to use an if:
```
if (Logger.isDebugEnabled(this)) {
    Logger.debug(this, "Some %s", calculate());
}
```

Which considering that java 8 introduced lambdas would be more clearly written as:
```
Logger.debug(this, "Some %s", this::calculate());
```

To achieve this and allow pre java 8 code to run it would be enough to introduce  a set of methods like:
```
public static void debug( final Object source, final String msg, final Supplier<?>... args) 
```

Where `Supplier` is an interface like the one in Java 8 (https://docs.oracle.com/javase/8/docs/api/java/util/function/Supplier.html) or Guava (https://google.github.io/guava/releases/19.0/api/docs/com/google/common/base/Supplier.html). We can introduce our own version of that to reduce dependencies. Java 8 will handle any interface as long as it has only one method.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@krzyk good idea, thanks

**Comment by dmarkov** [comment]
@krzyk thanks for the report, I topped your acc for 15 mins, payment ID `97304027`

**Comment by dmarkov** [comment]
@amihaiemil please proceed, it's yours

**Comment by amihaiemil** [comment]
@krzyk The way I understand it, you want to implement java8 ``::`` behaviour using Java 7 with an interface/class similar to ``Supplier``?
 
So you would call the ``logger.debug`` method like this:

``logger.debug(new Supplier("Some %s", this, "method-to-call"))`` ? - different than you suggested initally

and inside ``Supplier.get()`` you would have something like: 
```
if(Logger.isDebugEnabled(this.original)){
    //...use reflection somehow to find and method-to-call in this.original?
    Logger.debug(this.original, "Some %s", this.original.method())
}
``` 

Where ``this.original`` is the original reference which started everything, which was passed as the second arcument of ``new Supplier``

I know it's very twisted. So either it's much more complicated than you thought, or I got it wrong.

**Comment by krzyk** [comment]
@amihaiemil Why change the method signature?
The idea is that only the parameters are provided using suppliers, this way the usage of the method will be almost exactly like the current ones.

I was thinking of something like this:
```
public static void debug(final Object source, final String msg, final Supplier<?>... args) {
    if(Logger.isDebugEnabled(source)){
        Object[] interpolated = new Object[args.length];
        for (int i = 0; i < interpolated.length; i++) {
            interpolated[i] = args[i].get();
        }
        Logger.logger(source).debug(Logger.format(msg, interpolated));
    }
}
```

**Comment by amihaiemil** [comment]
@krzyk Ok, but I still have to use reflection, don't I? So an ``arg`` would be something like this: 
``new Supplier(source, "method-to-call")``. I changed the signature because you pass ``source`` to ``Supplier`` as well, and so you could also pass ``msg`` there, and do everything in ``Supplier.get`` .

**Comment by krzyk** [comment]
@amihaiemil Why reflections?
Why do you need to pass the source to the Supplier?

Supplier is as simple as:

```
public class Supplier<T> {
    private final T data;

    public Supplier(T data) {
        this.data = data;
    }

    public T get() {
        return this.data;
    }
}
```

**Comment by krzyk** [comment]
@amihaiemil It is responsibility of the lib user to provide the concrete Supplier implementation here.
When one has java 8 it would be very simple, by e.g. using `() -> Math.random()`, or `this::someCalculation()`

**Comment by amihaiemil** [comment]
@krzyk I see now, so you simply want to introduce java8's ``Supplier``; I thought you wanted to implement ``Supplier``, in which case reflection would have been necessary, because how else can ``T`` be a "method reference"

**Comment by krzyk** [comment]
@amihaiemil Yeas, I just want to use `Supplier`, not introduce lambda evaluation here :)

**Comment by amihaiemil** [comment]
@krzyk Is it ok with you if I add also the default-access class ``SuppliersLogger``, which will contain your methods (for trace, debug, info, warn and error)? and then the user would do
``Logger.withSupplier().debug(this, "Some %s", this::calculate());`` 

I think it's better to do it like this, because more sets of methods will come. ``Supplier`` is only for methods which take no arguments and return something. Then there is also ``Function<T, R>`` and ``Consumer``... the 3 of these mean a total of 15 methods (5 for each interface)... and ``Logger`` is already kind of big (~500 lines).

**Comment by krzyk** [comment]
@amihaiemil Yes, it sounds good.

**Comment by amihaiemil** [comment]
@dmarkov PR #85 is for this

**Comment by dmarkov** [comment]
> @dmarkov PR #85 is for this

@amihaiemil thank you!

**Comment by amihaiemil** [comment]
@dmarkov I need more time

**Comment by dmarkov** [comment]
> @dmarkov I need more time

@amihaiemil sure, thanks for telling me, take your time

**Comment by amihaiemil** [comment]
@krzyk the pr has been merged. Can u close this? Thanks

**Comment by krzyk** [comment]
@amihaiemil thanks

**Comment by dmarkov** [comment]
@amihaiemil I added **30 mins** to your account, many thanks for working with the project (AP-80670688HM044824D)! The completion time here was 358 hours and 23 mins.. +30 added to your rating, current score is: [+533](http://www.netbout.com/b/36402?open=rating)
