### ISSUE TITLE
Unify Logger API

### ISSUE THREAD

**Issue by prondzyn** [jcabi/jcabi-log#84]
The [Logger.java](https://github.com/jcabi/jcabi-log/blob/master/src/main/java/com/jcabi/log/Logger.java) API looks a little bit inconsistent now. There are methods: `trace`, `debug`, `info`, and `warn` which internally checks if appropriate logging level is enabled. There are methods `traceForced`, `debugForced`, `infoForced`, and `warnForced` which omits level checking. And there is `error` method with does not check the logging level internally. The method naming and behavior are now a little bit inconsistent. Maybe we should rename `error` to `errorForced` and provide new `error` method which will checks the logging level analogously to other methods?

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@prondzyn well, it's by design. We don't want people to have an ability to log an error conditionally. And an error is an error, we always want to see it in the log.

**Comment by prondzyn** [comment]
@yegor256 sounds ok for me. I'm closing then.
